---
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
 credentials: |-
   aws_access_key_id: $AWS_SECRET_ACCESS_KEY
   aws_secret_access_key: $AWS_ACCESS_KEY_ID
   region: $AWS_S3_REGION
   endpoint: $AWS_ENDPOINT_URL
data:
  aws_access_key_id: $AWS_SECRET_ACCESS_KEY_BASE64
  aws_secret_access_key: $AWS_ACCESS_KEY_ID_BASE64
  region: $AWS_S3_REGION_BASE64
  endpoint: $AWS_ENDPOINT_URL_BASE64