apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apmserver
spec:
  version: $ELASTIC_VERSION
  count: $ELASTIC_APMS_INSTANCES
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      nodeSelector:
        tier: $ELASTIC_APMS_TIER

# inject secure settings into APM Server keystore from k8s secrets references
# secureSettings:
# - secretName: ref-to-secret
# - secretName: another-ref-to-secret
#   # expose only a subset of the secret keys (optional)
#   entries:
#   - key: value1
#     path: newkey # project a key to a specific path (optional)