apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: $ELASTIC_VERSION
  count: $ELASTIC_KIBANA_INSTANCES
  elasticsearchRef:
    name: "elasticsearch"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    metadata:
      labels:
        # additional labels for pods
        component: kibana
    spec:
      nodeSelector:
        tier: $ELASTIC_KIBANA_TIER
      containers:
        - name: kibana
          resources:
            requests:
              memory: $ELASTIC_KIBANA_MEM_REQUEST
              cpu: $ELASTIC_KIBANA_CPU_REQUEST
            limits:
              memory: $ELASTIC_KIBANA_MEM_LIMIT
              cpu: $ELASTIC_KIBANA_CPU_LIMIT