apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: '$APP_NAME-tls'
  namespace: default
spec:
  secretName: '$APP_NAME-tls'
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - $DNS_WEBSITE
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod